Developasd
AdilkhanBerikov/podofcast pull request #2
Opened 2024-12-18 13:05 UTC by AdilkhanBerikov

2024-12-18 13:21 UTC, Ryockans commented on src/pages/index.html
> +          <ul class="first-block__list">
Плохой нейминг

2024-12-18 13:24 UTC, Ryockans commented on src/pages/css/components/footer/block.css
> +.first-block__list {
Нейминг

2024-12-18 13:24 UTC, Ryockans commented on src/pages/css/components/footer/block.css
> +    list-style: none;
Ресет css должен убрать стили списков

2024-12-18 13:25 UTC, Ryockans commented on src/pages/css/components/footer/block.css
> +    height: 222px;
Высота не нужна

2024-12-18 13:28 UTC, Ryockans commented on src/pages/css/components/footer/block.css
> +    height: 74px;
Плохая практика, не задавай высоту в :first-of-type 
:first-of-type  и :last-of-type используются для стилизации первого и последнего элемента списка, при этом не должно быть зависимости от конкретного блока

2024-12-18 13:28 UTC, Ryockans commented on src/pages/css/components/footer/block.css
> +    width: 122px;
Та же ошибка

2024-12-18 13:28 UTC, Ryockans commented on src/pages/css/components/footer/block.css
> +    height: 74px;
Для картинок можно задать длина + ширина

2024-12-18 13:29 UTC, Ryockans commented on src/pages/css/components/footer/block.css
> +    font-size: 14px;
Договаривались выносить в переменные

2024-12-19 05:53 UTC, AdilkhanBerikov commented on src/pages/css/components/footer/block.css
> +    height: 222px;
как тут сделать чтобы высота осталась 222

2024-12-19 05:56 UTC, AdilkhanBerikov commented on src/pages/css/components/footer/block.css
> +    height: 74px;
картинка почему то задана как 74 на 74
а вот сама коробка для этого лого почему то 79 идет странно

2024-12-20 04:09 UTC, Ryockans commented on src/pages/css/components/footer/block.css
> +    height: 222px;
Заданный gap как вариант
Вообще, гораздо лучше выставлять внутренние margin и gap'ы, чем задавать высоту

2024-12-20 04:10 UTC, Ryockans commented on src/pages/css/components/footer/general.css
> +    grid-template-columns: 1fr 414px 1fr;
Лучше обходиться без конкретных значений

2024-12-20 04:10 UTC, Ryockans commented on src/pages/css/components/footer/general.css
> +    padding-bottom: 137px;
Выглядит, так, будто это margin

2024-12-20 04:11 UTC, Ryockans commented on src/pages/css/components/footer/platforms.css
> +    height: 77px;
Опять высота

2024-12-20 04:11 UTC, Ryockans commented on src/pages/css/components/footer/platforms.css
> +    height: 22px;
Опять высота

2024-12-20 04:11 UTC, Ryockans commented on src/pages/css/components/footer/platforms.css
> +    height: 82px;
размеры

2024-12-20 04:11 UTC, Ryockans commented on src/pages/css/components/footer/platforms.css
> +    height: 36px;
размеры

2024-12-20 04:11 UTC, Ryockans commented on src/pages/css/components/header/dropdown.css
> +    background: url("data:image/svg+xml,%3Csvg%20class%3D%22arrow-down%22%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%2216%22%20height%3D%2216%22%20viewBox%3D%220%200%2016%2016%22%20fill%
Лучше ссылкой вставить

2024-12-20 04:12 UTC, Ryockans commented on src/pages/css/components/header/dropdown.css
> +    display: none; /* Скрываем меню по умолчанию */
Излишние комментарии

2024-12-20 04:12 UTC, Ryockans commented on src/pages/css/components/header/general.css
> +    height: 74px;
для картинки в свойствах задать ширина + высота

2024-12-20 04:13 UTC, Ryockans commented on src/pages/css/global.css
> +a:hover {
Лучше компонентом ссылок делать, на странице могут быть ссылки разных вариантов

2024-12-20 04:14 UTC, Ryockans commented on src/pages/css/libs/buttons.css
> +    border-radius: 8px;
Это можно вынести в переменную

2024-12-20 04:14 UTC, Ryockans commented on src/pages/css/libs/buttons.css
> +    border: 2px var(--color-black) solid;
обычно делают width style color

2024-12-22 10:14 UTC, Ryockans requested changes

2024-12-22 10:14 UTC, Ryockans commented on src/pages/css/components/footer/general.css
> +    border-top: 1px solid var(--color-footer-general-border); /*тут както надо сделать 1.5*/
Удали коммент)

2024-12-22 10:14 UTC, Ryockans commented on src/pages/css/components/footer/general.css
> +    border-top: 1px solid var(--color-footnote-general-border); /*тут както надо сделать 1.5*/
Тут тоже

2024-12-22 10:14 UTC, Ryockans commented on src/pages/css/components/footer/logo-socials.css
> +.footer__logo__socials {
Бэм пропал

2024-12-22 10:14 UTC, Ryockans commented on src/pages/css/components/header/dropdown.css
> +    padding: 6px 25px 6px 15px;
padding и margin далее пиши первым свойством

2024-12-22 10:14 UTC, Ryockans commented on src/pages/css/libs/buttons.css
> +    border-radius: 8px;
Про радиус забыл

2024-12-22 10:14 UTC, Ryockans commented on src/pages/css/variables/colors.css
> +    --color-a-link-text-hover: var(--color-vermillion);
просто link-hover

2024-12-22 10:14 UTC, Ryockans commented on src/pages/css/variables/fonts.css
>      --font-heading-h1: 700 59px/1.2 -0.02em var(--font-family-main);
Просто h1/2/3

2024-12-22 10:14 UTC, Ryockans commented on src/pages/index.html
> +        <div class="footer__logo__socials">
БЭМ

2024-12-23 08:04 UTC, merged