main first section landing
AdilkhanBerikov/podofcast pull request #3
Opened 2024-12-25 10:03 UTC by AdilkhanBerikov

2024-12-25 10:22 UTC, Ryockans requested changes
Уже лучше, но некоторые ошибки повторяются

2024-12-25 10:22 UTC, Ryockans commented on src/assets/css/components/common/grids.css
>      margin-top: 24px;
Делаем так, для отступов у каждого блока используем margin-bottom, margin-top используем только когда без него не обойтись

2024-12-25 10:22 UTC, Ryockans commented on src/assets/css/components/main/landing/background-elements.css
> +.landing-background__hero-shape-swirl {
Не так сделано, см коммент в веркстке

2024-12-25 10:22 UTC, Ryockans commented on src/assets/css/components/main/landing/covers.css
> +    width: 1160px;
smells like .container spirit

2024-12-25 10:22 UTC, Ryockans commented on src/assets/css/components/main/landing/covers.css
> +    margin-left: -393px;
Это лишнее

2024-12-25 10:22 UTC, Ryockans commented on src/assets/css/components/main/landing/covers.css
> +    line-height: 0;
Зачем?

2024-12-25 10:22 UTC, Ryockans commented on src/assets/css/components/main/landing/heading.css
> +    margin: 40px 0;
margin-bottom

2024-12-25 10:22 UTC, Ryockans commented on src/assets/css/components/main/landing/heading.css
> +.heading__text-black {
Лишний класс

2024-12-25 10:22 UTC, Ryockans commented on src/assets/css/components/main/landing/heading.css
> +.heading__text-vermillion {
лучше ..heading__accent

2024-12-25 10:22 UTC, Ryockans commented on src/assets/css/components/main/landing/platforms.css
> +    border-top: 1px solid var(--color-davys-grey);
можно прямо в компоененте завести переменную --border-platforms: 1px var(--color-davys-grey)

2024-12-25 10:22 UTC, Ryockans commented on src/assets/css/components/main/landing/platforms.css
> +    padding: 25px 73px;
Убрать, это плохо, компоненты соц сетей должны быть одинаковыми

2024-12-25 10:22 UTC, Ryockans commented on src/pages/index.html
> +      <section class="landing">
landing плохое название для секции

2024-12-25 10:22 UTC, Ryockans commented on src/pages/index.html
> +        <div class="landing-background__hero-shape-swirl">
Убираем, делаем единым бэкграундом для секции

2024-12-25 10:22 UTC, Ryockans commented on src/pages/index.html
> +        <div class="landing-background__three-stars">
Убираем

2024-12-25 10:22 UTC, Ryockans commented on src/pages/index.html
> +            <span class="heading__text-black">Your Daily</span>
Лишний span

2024-12-25 10:22 UTC, Ryockans commented on src/assets/css/libs/buttons.css
> +.heading__button-big {
Хм, выглядит как модификатор на кнопку

2024-12-25 10:22 UTC, Ryockans commented on src/pages/index.html
> +          <div class="footer-platforms">
footer__platforms platforms

2024-12-25 10:22 UTC, Ryockans commented on src/pages/index.html
> +            <ul class="footer-platforms__list">
platforms__list

2024-12-25 10:22 UTC, Ryockans commented on src/pages/index.html
> +          <div class="footer-apps">
footer__apps apps

2024-12-25 10:22 UTC, Ryockans commented on src/pages/index.html
> +            <ul class="footer-apps__list">
apps__list

2024-12-25 10:29 UTC, Ryockans commented
Еще название коммита лучше продумать нужно, типа:
"added home page heading section"

2024-12-25 11:59 UTC, AdilkhanBerikov commented on src/assets/css/components/common/grids.css
>      margin-top: 24px;
понял
а в данном случае они нужны?
мне их больше некуда пихнуть
только в логотип или новый див делать да?

2024-12-25 12:02 UTC, Ryockans commented on src/assets/css/components/common/grids.css
>      margin-top: 24px;
Не заметил, что это хедер
Да тут оставляем

2024-12-25 12:03 UTC, AdilkhanBerikov commented on src/assets/css/components/main/landing/background-elements.css
> +.landing-background__hero-shape-swirl {
где в верстке смотреть?

2024-12-25 12:04 UTC, AdilkhanBerikov commented on src/assets/css/components/main/landing/covers.css
> +    width: 1160px;
вот это не понял
у меня без ширины 5 картинок не выставляются почему то правильно, все смещается, не знаю как сделать

2024-12-25 12:06 UTC, AdilkhanBerikov commented on src/assets/css/components/main/landing/covers.css
> +    margin-left: -393px;
ты имеешь ввиду позицию?

2024-12-25 12:07 UTC, AdilkhanBerikov commented on src/assets/css/components/main/landing/covers.css
> +    line-height: 0;
опять тут логотипы все смещаются вверх на пару пикселей

2024-12-25 12:48 UTC, Ryockans commented on src/assets/css/components/main/landing/covers.css
> +    margin-left: -393px;
Да, фиксированный margin убрать

2024-12-25 12:49 UTC, Ryockans commented on src/assets/css/components/main/landing/covers.css
> +    line-height: 0;
Убери line-height

2024-12-25 12:49 UTC, Ryockans commented on src/assets/css/components/main/landing/background-elements.css
> +.landing-background__hero-shape-swirl {
По комментам ниже

2024-12-25 12:53 UTC, Ryockans commented on src/assets/css/components/main/landing/covers.css
> +    width: 1160px;
Можно либо накинуть контейнер с модификатором, без паддингов, либо вынести ширины в переменные

2024-12-25 14:59 UTC, AdilkhanBerikov commented on src/assets/css/libs/buttons.css
> +.heading__button-big {
ну это тот же баттон только чуть больше его как лучше сделать?

2024-12-25 15:00 UTC, AdilkhanBerikov commented on src/pages/index.html
> +            <ul class="footer-platforms__list">
я вот понял что у меня в css platforms в нескольких местах поэтому я сделал footer-platforms__list
как лучше тогда сделать

2024-12-25 16:38 UTC, Ryockans commented on src/pages/index.html
> +              <img src="../assets/images/covers/tesla-cover.png" alt="Tesla Autopilot Cover" width="373" height="373" class="covers__image">
Сделать полноценную карточку

2024-12-25 16:40 UTC, Ryockans commented on src/pages/index.html
> +            <ul class="footer-platforms__list">
Тогда нужно подумать, а не один и тот же это компонент
мб тогда .platfotms.-compact

2024-12-25 16:40 UTC, Ryockans commented on src/assets/css/libs/buttons.css
> +.heading__button-big {
Модификатор на кнопку сделать, как с цветом, только теперь с размером

2024-12-26 06:02 UTC, AdilkhanBerikov commented on src/assets/css/components/main/landing/covers.css
> +    margin-left: -393px;
убрал, сделал это:
.landing-covers__list {
    display: flex;
    justify-content: center;
    gap: 20px;
}

2024-12-26 06:03 UTC, AdilkhanBerikov commented on src/assets/css/components/main/landing/covers.css
> +    width: 1160px;
убрал, сделал это 
grid-template-rows: min-content;
    grid-template-columns: repeat(12, 78px);
    gap: 20px;
    
    .landing {
    grid-column: 1 / 13;
    position: relative;
}

2024-12-26 06:06 UTC, Ryockans commented on src/assets/css/components/main/landing/covers.css
> +    width: 1160px;
Выглядит страшно
```
grid-template-columns: repeat(12, 78px);
```
Нельзя без этого?

2024-12-26 06:10 UTC, AdilkhanBerikov commented on src/assets/css/components/main/landing/covers.css
> +    line-height: 0;
убрал
Все картинки сместились на 4 px вверх

2024-12-26 06:13 UTC, AdilkhanBerikov commented on src/assets/css/components/main/landing/heading.css
> +    margin: 40px 0;
вот тут не понял
сделать margin bottom and top отдельно?

2024-12-26 06:37 UTC, AdilkhanBerikov commented on src/assets/css/components/main/landing/heading.css
> +.heading__text-black {
убрал

2024-12-26 06:37 UTC, AdilkhanBerikov commented on src/assets/css/components/main/landing/heading.css
> +.heading__text-vermillion {
добавил и оставил только один span

2024-12-26 10:51 UTC, AdilkhanBerikov commented on src/assets/css/components/main/landing/platforms.css
> +    padding: 25px 73px;
сделал, все поменял там, через гриды сделал

2024-12-26 11:04 UTC, AdilkhanBerikov commented on src/pages/index.html
> +      <section class="landing">
как можно назвать, голову щас сломаю над названием))
у меня есть вариант header-title

2024-12-26 20:30 UTC, AdilkhanBerikov commented on src/assets/css/libs/buttons.css
> +.heading__button-big {
тут я не понял, мне к марджинам и паддингам модификаторы поставить?

2024-12-26 20:30 UTC, AdilkhanBerikov commented on src/pages/index.html
> +          <div class="footer-platforms">
тут я не понял, я сравнивал платформс в мейне и в футере, у них чуть чуть разные настройки

2024-12-26 20:32 UTC, AdilkhanBerikov commented on src/pages/index.html
> +            <ul class="footer-platforms__list">
тут я не понял, я сравнивал платформс в мейне и в футере, у них чуть чуть разные настройки
для чего платформс добавить нужно
только если установить дисплей флекс

2024-12-26 20:33 UTC, AdilkhanBerikov commented on src/pages/index.html
> +          <div class="footer-apps">
тут аналогично не понял как с платформс

2024-12-26 20:33 UTC, AdilkhanBerikov commented on src/pages/index.html
> +            <ul class="footer-apps__list">
тут аналогично не понял как с платформс

2024-12-27 07:40 UTC, Ryockans requested changes

2024-12-27 07:40 UTC, Ryockans commented on src/assets/css/components/main/general.css
>      background-color: var(--color-main-landing-background);
Цвет накинуть на секцию

2024-12-27 07:40 UTC, Ryockans commented on src/assets/css/components/main/main-section/covers.css
> +}
Лишний стиль

2024-12-27 07:40 UTC, Ryockans commented on src/assets/css/components/main/main-section/covers.css
> +}
Еще один

2024-12-27 07:40 UTC, Ryockans commented on src/assets/css/components/main/main-section/covers.css
> +}
background-repeat: no-repeat;
    background-size: 373px;
    Повторил 5 раз

2024-12-27 07:40 UTC, Ryockans commented on src/assets/css/components/common/grids.css
> +    grid-template-columns: repeat(12, 1fr);
Зачем?

2024-12-27 07:40 UTC, Ryockans commented on src/assets/css/components/main/main-section/general.css
> +    position: relative;
Этим ты убрал смысл в верхнем гриде

2024-12-27 07:40 UTC, Ryockans commented on src/assets/css/libs/buttons.css
> +    background: var(--color-button-hover-background);
Что-то странное, в libs не должно быть таких конструкций
Только button и его модификаторы

2024-12-27 07:40 UTC, Ryockans commented on src/assets/css/variables/borders.css
> +    --border-radius-cover: 12px;
--border-radius-large

2024-12-27 07:40 UTC, Ryockans commented on src/assets/css/variables/dimensions.css
> +    --main-section-cover-width: 373px;
Не, это не универсальная переменная, лучше хранить в стилях компонентов карточек

2024-12-27 07:40 UTC, Ryockans commented on src/pages/index.html
> +              <article class="cover tesla-cover">
Это не article
Больше на это похоже https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure

2024-12-27 07:44 UTC, Ryockans commented on src/assets/css/components/main/landing/heading.css
> +    margin: 40px 0;
Тут нет вопросов, перепутал с другим блоком

2024-12-27 07:45 UTC, Ryockans commented on src/assets/css/libs/buttons.css
> +.heading__button-big {
Тут должно быть .button.-big

2024-12-27 07:46 UTC, Ryockans commented on src/pages/index.html
> +          <div class="footer-platforms">
Ладно, можем оставить, тогда поставь footer__platforms по БЭМу

2024-12-27 07:48 UTC, Ryockans commented on src/pages/index.html
> +            <ul class="footer-platforms__list">
Либо можно вынести platform-list в отдельный компонент, только 3 картинки платформ и  уже его прокидывать
Но пока можем и забить

2024-12-27 07:48 UTC, Ryockans commented on src/pages/index.html
> +          <div class="footer-apps">
БЭМ потерялся

2024-12-27 07:48 UTC, Ryockans commented on src/pages/index.html
> +            <ul class="footer-apps__list">
Можно пока оставить

2024-12-27 10:13 UTC, AdilkhanBerikov commented on src/assets/css/components/main/main-section/covers.css
> +}
ты имеешь ввиду убрать их из html или просто изза того что стиля нету на них

2024-12-27 10:13 UTC, AdilkhanBerikov commented on src/assets/css/components/main/main-section/covers.css
> +}
ты имеешь ввиду убрать их из html или просто изза того что стиля нету на них

2024-12-27 10:15 UTC, Ryockans commented on src/assets/css/components/main/main-section/covers.css
> +}
Стили пустые убрать из css, но оставь классы в html

2024-12-27 10:44 UTC, AdilkhanBerikov commented on src/assets/css/components/main/general.css
>      background-color: var(--color-main-landing-background);
под page main вставил див wrapper и туда накинул бэк

2024-12-27 11:11 UTC, AdilkhanBerikov commented on src/assets/css/variables/dimensions.css
> +    --main-section-cover-width: 373px;
убрал их и поставил в covers css 373 пикселя
ты ж это имел ввиду правильно?

2024-12-27 11:27 UTC, AdilkhanBerikov commented on src/assets/css/components/common/grids.css
> +    grid-template-columns: repeat(12, 1fr);
тут непонял, мне нужно чтобы контент был посередине

2024-12-27 12:32 UTC, Ryockans commented on src/assets/css/components/common/grids.css
> +    grid-template-columns: repeat(12, 1fr);
А как 12 колонок решают первую проблему
По второму пункту вообще не согласен, ты будешь прокидывать секции, так же как и сейчас

2024-12-27 12:32 UTC, Ryockans commented on src/assets/css/variables/dimensions.css
> +    --main-section-cover-width: 373px;
Завести переменную в стилях карточки

2024-12-29 15:10 UTC, Ryockans requested changes
Удалить комменты из кода

2024-12-29 15:10 UTC, Ryockans commented on src/assets/css/libs/buttons.css
> +.button.big {
.button.-big

2024-12-29 15:10 UTC, Ryockans commented on src/assets/css/libs/buttons.css
>      margin: 60px 0 120px 0;
margin не относятся к кнопке

2024-12-29 15:10 UTC, Ryockans commented on src/pages/index.html
> +              <figure class="cover tesla-cover">
Убрать классы бэкграундов и использовать img

2024-12-29 15:10 UTC, Ryockans commented on src/assets/css/components/main/main-section/covers.css
> +    width: 373px;
Переменная должна быть

2024-12-29 15:10 UTC, Ryockans commented on src/assets/css/components/main/main-section/general.css
>  .main-section::before {
Убрать before

2024-12-29 15:10 UTC, Ryockans commented on src/assets/css/components/main/main-section/heading.css
> +    padding: 40px 0;
padding-top и margin-bottom

2024-12-29 15:10 UTC, Ryockans commented on src/assets/css/components/main/main-section/platforms.css
> +    margin-top: 120px;
Перенести в другой компонент margin-bottom

2024-12-29 15:10 UTC, Ryockans commented on src/pages/index.html
>                  <h2 class="cover__heading">Tesla Autopilot</h2>
figcaption

2024-12-29 15:13 UTC, Ryockans commented
cursor: pointer  в button добавить

2024-12-30 07:32 UTC, merged